baseURL: ""
languageCode: en-us
title: Excel Ojo
paginate: 5
theme: PaperMod

menu:
  main:
    - identifier: home
      name: i'm
      url: /
      weight: 1
    - identifier: journal
      name: journal
      url: /journal
      weight: 2
    - identifier: project
      name: projects
      url: /project
      weight: 3
    - identifier: all
      name: all
      url: /daall
      weight: 4
    # - identifier: search
    #   name: Search
    #   url: /search
    #   weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  hideMeta: false

  assets:
    favicon: favicon.ico
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple-touch-icon.png
    safari_pinned_tab: safari-pinned-tab.svg


  # for enchanced SEO
  env: production

  defaultTheme: auto
  disableThemeToggle: true
  ShowReadingTime: true


  label: 
    text: "@dudeiebot"
    icon: "dp2.png"
    iconHeight: 25
  # Home Page
  profileMode:
    enabled: true
    title: "_id~_"
    subtitle: | 
      Hi there, I am Excel - a software expert. I spend my days hacking on open source projects(mostly my own and private). You can bet I am not out here trying to break stuff; it is all about the joy of creating and exploring technology in a secure world. Here is my [RSSfeed](/journal/index.xml)
    imageUrl: "suare.jpg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: da'setup🛠️
        url: "setup"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "linkedin" 
      url: "https://www.linkedin.com/in/excel-ojo/"
    - name: "twitter"
      url: "https://twitter.com/crecia_cell"
    - name: "github"
      url: "https://github.com/dudeiebot"
    - name: "mail"
      url: "mailto:ojoexcel5@gmail.com"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
